# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "Deploy to Firebase app distribution"
 lane :deploy do
 begin
  firebase_app_distribution(
   #groups: "testers",
   release_notes: "Fixing bug in features",
   apk_path: "build/app/outputs/apk/release/app-release.apk",     #"../build/app/outputs/flutter-apk/app-release.apk",
   #firebase_cli_path: "/usr/local/bin/firebase",
   firebase_cli_token: "1//0g-b8IIDzVQLRCgYIARAAGBASNwF-L9IrT2Wt5mBHFZHY_dzb9MdJXtlxlT4dL48OgUqpzQTa7_1fLuAAG68tXF1rQdc4598wnaY",
   app: "1:401274130458:android:921723741c07dfa263c1a3"
   #debug: true
   )
  end
 end
end