name: Slack notifcation 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  slack-notification:
    name: slack Notification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@2    
          SLACK_CHANNEL: watchtower-alert
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #./build/app/outputs/apk/release/my-app.apk
  #    - uses: actions/upload-artifact@v1
  #    - with:
  #        name: app
  #        path: app/build/outputs/apk/debug/app-debug.apk

  #    - run: flutter pub get
  #    - run: dart format --output=none --set-exit-if-changed .
  #    - run: dart analyze
  #    - run: dart test



      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      #- name: Analyze project source
      #  run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
      #  run: dart test
