name: Build by Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@2

    - name: Set up Ruby enviroment
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: 3.0.2
        bundler-cache: true
 
    - name: Run tests
      run: bundle exec fastlane android test